# Generated by Django 5.2.1 on 2025-05-13 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pdf_file', models.FileField(upload_to='submissions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRefundConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_price', models.DecimalField(decimal_places=2, default=90.0, max_digits=6)),
                ('amend_price', models.DecimalField(decimal_places=2, default=99.0, max_digits=6)),
                ('locker_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
            ],
        ),
    ]
