# Generated by Django 5.2.1 on 2025-05-13 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_refund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCode',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('file', 'File my U.S. Non-Resident Taxes'), ('amend', 'Amend my U.S. Taxes')], max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('promo_ends_at', models.DateTimeField(blank=True, null=True)),
                ('creator_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('address_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
