# Generated by Django 5.2.1 on 2025-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_refund', '0002_creatorcode_servicepricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrefundconfig',
            name='justfederal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxrefundconfig',
            name='amend_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxrefundconfig',
            name='file_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxrefundconfig',
            name='locker_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
